export const GET_ARTICLE_DATA = "GET_ARTICLE_DATA" 
export const GET_SINGLE_ARTICLE_DATA = "GET_SINGLE_ARTICLE_DATA"
export const BACK_TO_ARTICLES_LIST = "BACK_TO_ARTICLES_LIST"
export const SELECT_CATEGORY = 'SELECT_CATEGORY'
export const AUTHENTICATE = 'AUTHENTICATE'
export const SHOW_LOGIN_FORM = "SHOW_LOGIN_FORM";